### ISSUE TITLE
Forks can still be found

### ISSUE THREAD

**Issue by tobijdc** [paulograbin/hybris-integration-intellij-idea-plugin#2]
With the following search you can still finds forks of the repository before it was delete or made private
https://github.com/search?l=&o=desc&q=hybris-integration-intellij-idea-plugin+fork%3Atrue&s=updated&type=Repositories

**Comment by paulograbin** [comment]
Hi Tobias, thanks for you comment. 

I didn't know you needed to add the flag fork: true to actually find something.
What I did is to go after the contributors using Google's cache and ended up finding a bunch of them.

Since the original owner deleted the instructions, my plan is to create a set of instructions on how to set up the project environment and continue development from there.

**Comment by Janhouse** [comment]
I renamed my fork, removed the analytics tracking code and submitted it to JetBrains plugin repo for review.
Compiled plugin zip is available in my repository releases section while JetBrains is reviewing it.

**Comment by Janhouse** [comment]
It has been approved in JetBrains store, feel free to install it from IntelliJ by searching for hybris integration or sap commerce integration.

https://plugins.jetbrains.com/plugin/12639-integration-for-sap-commerce

**Comment by paulograbin** [comment]
Good to hear that @Janhouse.
I've updated this repo's readme file to point everybody to yours.

**Comment by tobijdc** [comment]
Good, I think I can close the issue now
